config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'home/index'

  root 'home#index'

  resources :users, only: [:new, :create, :edit, :update, :show]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
  resources :articles do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

  get "/about" => "home#about"

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  belongs_to :category
  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :title, presence: true,
                    length: { minimum: 5 }


  def self.search(search)
    if search
      self.where("name like ?", "%#{search}%")
    else
      self.all
    end
  end

    def new_first_comments
      comments.order(created_at: :desc)
    end

    def like_for(user)
      likes.find_by_user_id(user)
    end

    def tag_names=(names)
      self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
      end
    end

    def tag_names
      self.tags.map(&:name).join(", ")
    end

    paginates_per 10

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

before_action :authorize_user, only: [:edit, :update, :destroy]
before_action :authenticate_user!, except: [:index, :show]
before_action :find_article, only: [:show, :edit, :update, :destroy]


  def index
    @articles = Article.all
    @a = Article.ransack(params[:q])
    @people = @a.result(distinct: true)
    @articles = Article.order(:title).page params[:page]
  end

def edit
  redirect_to root_path, alert: "access defined" unless can? :edit, @article
end

  def show
    @comment = Comment.new
    @like = @article.like_for(current_user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article Created!"
      redirect_to article_path(@article)
    else
      flash[:alert] = "Article not created!"
      render :new
    end
  end

  def update
    redirect_to root_path, alert: "access denined" unless can? :update, @article
    if @article.update article_params
      redirect_to article_path(@article), notice: "Article Updated"
    else
      render :edit
    end

  end

  def destroy
    redirect_to root_path, alert: "access denined" unless can? :destroy, @article
    @article.destroy
    redirect_to articles_path, notice: "Questions deleted"
  end

  private
    def article_params
      params.require(:article).permit(:title, :text, :category_id, :user_id, :tag_names)
    end

    def find_article
      @article = Article.find params[:id]
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article do |f| %>
  <div class="container">
    <p>
      <%= f.input :title %>
    </p>
    <p>
      <%= f.input :text, {rows: "10", cols: "50"}%>
    </p>
      <%= f.input :category_id, :collection => Category.all %>
    <div>
      <%= f.text_field :tag_names, placeholder: "Tags separated with comma" %>
    </div>
    <p>
      <%= f.submit %>
    </p>
  </div>
  <% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
<p><%= button_to "Submit a New Request", new_article_path, :method => :get %></p>

<%= search_form_for @a do |f| %>
  <%= f.label :name_cont %>
  <%= f.search_field :title_cont %>
  <%= f.submit %>

<% end %>
<% if @articles.present? %>
  <%= render @articles %>
<% else %>
  <p>There are no requests containing the term(s) <%= params[:search] %>.</p>
<% end %><br>
<br>

<div>
<table width='100%' border="1">
  <tr>
    <th style="text-align:center">Title</th>
    <th style="text-align:center">Text</th>
    <% if can? :edit, @article %>
    <th style="text-align:center">Actions</th>
    <% end %>
    <th style="text-align:center">Tags</th>
  </tr>

  <% @articles.each do |s| %>
    <tr style="text-align:center">
      <td><%= link_to s.title, article_path(s) %></td>
      <td><%= truncate(s.text, length: 50) %></td>
      <% if can? :edit, @article %>
      <td><%= link_to 'Edit', edit_article_path(s) %>
      <% end %>
      <% if can? :destroy, @article %>
      <%= link_to 'Delete', article_path(s),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      <td><%= s.tag_names %></td>
    </tr>
  <% end %>
  <%= paginate @articles %>
</table>
</div>
<br />

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="article-header">
  <h1>Article</h1>
</div>
<div class="article-title">
  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>
</div>
<div class="article-body">
  <p>
    <strong>Text:</strong>
    <%= @article.text %>
  </p>
</div>
<div class="article-tags">
  <strong>Tags: </strong>
  <%= @article.tag_names %>
</div>

<% if @like.present? && @like.persisted? %>
  <%= link_to "Un-Like", article_like_path(@article, @like), method: :delete %>
<% else %>
  <%= link_to "Like", article_likes_path(@article), method: :post %>
<% end %>

<% if can? :edit, @article %>
  <%= link_to "Edit", edit_article_path(@article) %>
<% end %>

<% if can? :destroy, @article %>
  <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>
<h2>Make a Comment</h2>
<%= simple_form_for [@article, @comment] do |f| %>
  <div class="container">
    <%= f.input :body %>
    <br />
    <%= f.button :submit %>
  </div>
<% end %>

<h3>Comments</h3>
<% @article.new_first_comments.each do |comms| %>
  <strong>Body :</strong>
  <%= comms.body %> <br />
  <% if can? :destroy, comms  %>
    <%= link_to "Delete", [@article, comms], method: :delete, data: {confirm: "Are you sure?"} %>
  <% end %>
<% end %>
<%= link_to 'Back', articles_path %>